name: Security Headers Check

on:
  schedule:
    # Run daily at 9 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  check-headers:
    if: ${{ secrets.PRODUCTION_URL != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check Security Headers
        run: |
          if [ -z "${{ secrets.PRODUCTION_URL }}" ]; then
            echo "Skipping security header check (PRODUCTION_URL not set)."
            exit 0
          fi

          echo "Checking security headers..."

          # Follow redirects (-L) and capture final status and headers
          status=$(curl -sS -L -D /tmp/headers.txt -o /dev/null -w "%{http_code}" "${{ secrets.PRODUCTION_URL }}")

          echo "HTTP status: $status"
          echo "---- Response headers (final) ----"
          cat /tmp/headers.txt
          echo "----------------------------------"

          if [ "$status" -lt 200 ] || [ "$status" -ge 400 ]; then
            echo "❌ Non-success HTTP status from PRODUCTION_URL"
            exit 1
          fi

          # Check for required security headers (case-insensitive, anchored)
          if ! grep -qi '^x-content-type-options: *nosniff' /tmp/headers.txt; then
            echo "❌ Missing X-Content-Type-Options: nosniff"
            exit 1
          fi

          if ! grep -qi '^x-frame-options: *deny' /tmp/headers.txt; then
            echo "❌ Missing X-Frame-Options: DENY"
            exit 1
          fi

          if ! grep -qi '^strict-transport-security:' /tmp/headers.txt; then
            echo "❌ Missing Strict-Transport-Security"
            exit 1
          fi

          echo "✅ All security headers present"
          grep -iE '^(x-content-type-options|x-frame-options|strict-transport-security|referrer-policy):' /tmp/headers.txt || true
